export const GET_CONTACTS_LOAD = "GET_CONTACTS_LOAD"
export const GET_CONTACTS_SUCCES = "GET_CONTACTS_SUCCES"
export const GET_CONTACTS_FAILED = "GET_CONTACTS_FAILED"
export const GET_CONTACT = "GET_CONTACT"

export const TOGGLE_TRUE ="TOGGLE_TRUE"
export const TOGGLE_FALSE ="TOGGLE_FALSE"
